import { Product } from '@/types';

/** Productos de demostración para mostrar la UI cuando el backend no está disponible */
export const MOCK_MEN_PRODUCTS: Product[] = [
  {
    id: 'mock-h1',
    name: 'Camisa Oxford Premium',
    description: 'Camisa de algodón pima 100% con corte slim y acabados en nácar.',
    price: 189000,
    stock: 12,
    category: 'Camisas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-h2',
    name: 'Camisa Lino Mediterráneo',
    description: 'Tejido en lino natural, perfecta para ocasiones formales y casuales.',
    price: 215000,
    stock: 8,
    category: 'Camisas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-h3',
    name: 'Pantalón Chino Clásico',
    description: 'Corte recto en gabardina elástica. Comodidad y estilo para todo el día.',
    price: 245000,
    stock: 15,
    category: 'Pantalones',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-h4',
    name: 'Pantalón Jogging Luxury',
    description: 'Tejido modal suave con cinturilla elástica y bolsillos con cierre.',
    price: 198000,
    stock: 6,
    category: 'Pantalones',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-h5',
    name: 'Chaqueta Bomber Italiana',
    description: 'Bomber en sarga de seda con forro interior estampado. Edición limitada.',
    price: 520000,
    stock: 4,
    category: 'Chaquetas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-h6',
    name: 'Blazer Estructurado',
    description: 'Blazer en lana merino con solapas satinadas. Versatil y elegante.',
    price: 680000,
    stock: 9,
    category: 'Chaquetas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-h7',
    name: 'Set Interior Modal',
    description: 'Camiseta y boxers en modal premium. Suavidad superior garantizada.',
    price: 145000,
    stock: 20,
    category: 'Ropa Interior',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-h8',
    name: 'Cinturón Cuero Artesanal',
    description: 'Cuero full-grain curtido al vegetal, hebilla de latón. Hecho a mano.',
    price: 175000,
    stock: 3,
    category: 'Accesorios',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
];

export const MOCK_WOMEN_PRODUCTS: Product[] = [
  {
    id: 'mock-m1',
    name: 'Vestido Midi Satén',
    description: 'Satén fluido con escote V y manga larga. Elegancia para cada ocasión.',
    price: 385000,
    stock: 7,
    category: 'Vestidos',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-m2',
    name: 'Vestido Wrap Floral',
    description: 'Estampado exclusivo en gasa ligera. Corte envolvente favorecedor.',
    price: 295000,
    stock: 11,
    category: 'Vestidos',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-m3',
    name: 'Blusa Francesa Bordada',
    description: 'Bordados artesanales en algodón orgánico. Manga globo y cuello bebé.',
    price: 225000,
    stock: 14,
    category: 'Blusas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-m4',
    name: 'Top Seda Natural',
    description: 'Top sin tirantes en seda pura con tirillas finas regulables.',
    price: 195000,
    stock: 5,
    category: 'Blusas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-m5',
    name: 'Pantalón Wide Leg',
    description: 'Pierna ancha en crepé de alta calidad. Tiro alto y bolsillos laterales.',
    price: 265000,
    stock: 10,
    category: 'Pantalones',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-m6',
    name: 'Chaqueta Tweed Premium',
    description: 'Tejido tweed artesanal con botones dorados. Inspiración couture.',
    price: 595000,
    stock: 6,
    category: 'Chaquetas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-m7',
    name: 'Blazer Oversize Cream',
    description: 'Blazer oversized en lana virgen. Botón único y solapas amplias.',
    price: 545000,
    stock: 8,
    category: 'Chaquetas',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'mock-m8',
    name: 'Collar Perlas Cultivadas',
    description: 'Perlas cultivadas de agua dulce en hilo de seda. Cierre en plata 925.',
    price: 320000,
    stock: 4,
    category: 'Accesorios',
    imageUrl: null,
    createdAt: '',
    updatedAt: '',
  },
];

export const ALL_MOCK_PRODUCTS: Product[] = [
  ...MOCK_MEN_PRODUCTS,
  ...MOCK_WOMEN_PRODUCTS,
];
